# Project information
site_name: 'Your site name'
site_description: 'Your site description'
site_author: 'Ruslan Iskov'

use_directory_urls: false
strict: true
dev_addr: '127.0.0.1:8010'

site_dir: '.\docs'
docs_dir: '.\source'

# site_url: 'https://squidfunk.github.io/mkdocs-material/'



# Repository
### repo_name: 'squidfunk/mkdocs-material'
### repo_url: 'https://github.com/squidfunk/mkdocs-material'
# repo_name: 'ruslan.rv.ua'
# repo_url: 'http://ruslan-rv-ua.github.io/'
# remote_branch: master


# Copyright
copyright: 'Copyright &copy; Руслан Іськов'

# Configuration
theme:
  name: material
  # logo: material/library
  palette:
    scheme: slate # default
    primary: 'black'
    accent: 'yellow'
  features:
    - navigation.instant
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    # - toc.integrate

# css overrides to make high contrast theme
extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css

# switch off plugins, it's for removing 'search' feature
plugins: []
#plugins:
#  - search
#  - awesome-pages:
#    collapse_single_pages: true
        
# Customization
#extra:
#   social:
#    - type: 'github'
#      link: 'https://github.com/squidfunk'
#    - type: 'twitter'
#      link: 'https://twitter.com/squidfunk'
#    - type: 'linkedin'
#      link: 'https://linkedin.com/in/squidfunk'
#    search:
#        language: 'en, ru'
    

# Google Analytics
# google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'

# Extensions
markdown_extensions:
#  - toc:
#      permalink: false
  - admonition
  - codehilite:
      guess_lang: false
      css_class: codehilite
      # pygments_style: agate
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: false
  - pymdownx.tilde

nav:
  - Some folder:
    - "some File": "some_folder/some.md"
  - Another:
    - Another file: "another_folder/another_file.md"